### ISSUE TITLE
[REQUEST] can you make this for me 

### ISSUE THREAD

**Issue by jbro129** [MarcuzD/TerraInveditDroid#12]
I was wondering if you could make a Windows application that could decrypt Terraria binary (iOS) and allow to be edited a friend of mine named tcikotci already made one but he's not going to release it (he enabled dev mode so he can use reds wings and it won't disappear)

**Comment by MarcuzD** [comment]
1) I'm not on windows, so no
2) I don't have any apple product, because they are so frickin' expensive, so no
3) since I'm still reverse-engineering the Terraria binary, I don't yet have the Blowfish keys, so I can't write a decryptor yet
4) dev mode? what? I had Red's wings, and it didn't disappear...

**Comment by jbro129** [comment]
If/when you get the keys can you leak them? If not can you atleast tell me? I'm working on a way to decrypt the saves/iOS Terraria binary but I can't cuz I don't have the keys

**Comment by MarcuzD** [comment]
I won't leak the keys.

**Comment by jbro129** [comment]
Can you atleast tell me when so I can decrypt my iOS devices Terraria binary

**Comment by MarcuzD** [comment]
I don't know when, and I don't have an apple product, so I don't know how to do it for ios.

**Comment by jbro129** [comment]
Can you atleast tell me the key?

**Comment by jbro129** [comment]
After you find it

**Comment by MarcuzD** [comment]
As I said, no. Period.
